# Generated by Django 5.2 on 2025-04-10 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'বিভাগ', 'verbose_name_plural': 'বিভাগসমূহ'},
        ),
        migrations.AddField(
            model_name='department',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='যোগাযোগ ইমেইল'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='বিভাগ কোড'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='core.faculty', verbose_name='বিভাগীয় প্রধান'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='বিবরণ'),
        ),
        migrations.AlterField(
            model_name='department',
            name='established',
            field=models.DateField(verbose_name='প্রতিষ্ঠার তারিখ'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='বিভাগের নাম'),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('academic', 'একাডেমিক'), ('admission', 'ভর্তি'), ('examination', 'পরীক্ষা'), ('event', 'অনুষ্ঠান'), ('other', 'অন্যান্য')], max_length=20),
        ),
    ]
