# Generated by Django 5.2 on 2025-04-16 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_department_options_department_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('ans', models.TextField()),
                ('page', models.CharField(choices=[('Admission', 'Admission'), ('Contuct', 'Contuct'), ('Notice', 'Notice')])),
            ],
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.RemoveField(
            model_name='department',
            name='contact_email',
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_department', to='core.faculty'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='established',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Vice Principal', 'Vice Principal'), ('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Lecturer', 'Lecturer'), ('Staff', 'Staff')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('campus', 'Campus'), ('event', 'Event'), ('student', 'Student Activities'), ('other', 'Other')], max_length=20),
        ),
    ]
