# Generated by Django 5.2 on 2025-04-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_faq_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='page',
            field=models.CharField(choices=[('Admission', 'Admission'), ('Contact', 'Contact'), ('Notice', 'Notice')]),
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('routin', 'রুটিন'), ('academic', 'একাডেমিক'), ('admission', 'ভর্তি'), ('examination', 'পরীক্ষা'), ('event', 'অনুষ্ঠান'), ('other', 'অন্যান্য')], max_length=20),
        ),
    ]
