# Generated by Django 5.2 on 2025-04-18 13:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_event_date_alter_faq_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('অধ্যক্ষ', 'অধ্যক্ষ'), ('সহযোগী অধ্যক্ষ', 'সহযোগী অধ্যক্ষ'), ('অধ্যাপক', 'অধ্যাপক'), ('যুগ্ম অধ্যাপক', 'যুগ্ম অধ্যাপক'), ('সহযোগী অধ্যাপক', 'সহযোগী অধ্যাপক'), ('প্রভাষক', 'প্রভাষক'), ('কর্মচারী', 'কর্মচারী')], max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
