# Generated by Django 5.2 on 2025-04-18 15:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_faculty_designation_alter_faculty_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['designation', 'name'], 'verbose_name_plural': 'Faculty Members'},
        ),
        migrations.AddField(
            model_name='notice',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('campus', 'ক্যাম্পাস'), ('event', 'ইভেন্ট'), ('students activity', 'ছাত্র কার্যক্রম'), ('other', 'অন্যান্য')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('রুটিন', 'রুটিন'), ('একাডেমিক', 'একাডেমিক'), ('ভর্তি', 'ভর্তি'), ('পরীক্ষা', 'পরীক্ষা'), ('অনুষ্ঠান', 'অনুষ্ঠান'), ('অন্যান্য', 'অন্যান্য')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notice',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document'),
        ),
    ]
