# Generated by Django 5.2 on 2025-04-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_notice_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='is_featured',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('principal', 'অধ্যক্ষ'), ('vice principal', 'সহযোগী অধ্যক্ষ'), ('professor', 'অধ্যাপক'), ('associate professor', 'যুগ্ম অধ্যাপক'), ('assistant professor', 'সহযোগী অধ্যাপক'), ('lecturer', 'প্রভাষক'), ('staff', 'কর্মচারী')], max_length=50),
        ),
        migrations.AlterField(
            model_name='faq',
            name='page',
            field=models.CharField(choices=[('admission', 'ভর্তি'), ('contact', 'যোগাযোগ'), ('notice', 'নোটিশ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('routine', 'রুটিন'), ('academic', 'একাডেমিক'), ('admission', 'ভর্তি'), ('exam', 'পরীক্ষা'), ('event', 'অনুষ্ঠান'), ('other', 'অন্যান্য')], max_length=20),
        ),
    ]
